services:
  proyectojpa1:
    build: proyectojpa1
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql-proyectojpa1:3306/springprueba?createDatabaseIfNotExist=true&serverTimeZone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: root
      SPRING_PROFILES_ACTIVE: docker
    restart: always
    depends_on:
      mysql-proyectojpa1:
        condition: service_healthy

  mysql-proyectojpa1:
    image: mysql:8.0.33
    container_name: mysql-proyectojpa1
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: springprueba
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" , "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 10
      start_period: 30s
